branches: ['main']

plugins:
  - "@semantic-release/commit-analyzer"
  - "@felixfbecker/semantic-release-docker"
  - - "@semantic-release/exec"
    - prepareCmd: "
        docker build -t csye7125group01/java_image .
        docker push csye7125group01/java_image
        "
  # - "@semantic-release/release-notes-generator"
  # - "@semantic-release/changelog"
  # - - "@semantic-release/git"
  #   - assets:
  #       - CHANGELOG.md
  #       - index.yaml
  #       - Chart.yaml
  #     message: |
  #       chore(release): version ${nextRelease.version}
  #       \n
  #       \n
  #       ${nextRelease.notes}
  # - - "@semantic-release/github"
    - assets:
        - path:
            - dist/*tgz
repositoryUrl: https://github.com/csye7125-fall2022-group01/webapp.git